### ISSUE TITLE
bugs on 2062 jeth calendar

### ISSUE THREAD

**Issue by dgfool** [RajuPrasai/NepDate#17]
bugs on 2062 jeth calendar

**Comment by RajuPrasai** [comment]
Thanks @dgfool , the issue has been identified and resolved.

**Comment by sanamhub** [comment]
@TheCrossLegCoder when you will publish those fixes as release btw?

**Comment by neapes** [comment]
@TheCrossLegCoder The issue has been closed, but the package has not been deployed yet, which is causing some production issues. We hope you can deploy it as soon as possible. We greatly appreciate your contribution to the .NET developer community in Nepal. 

FYI @dgfool

**Comment by RajuPrasai** [comment]
@neapes new version is now deployed in nuget : [2.0.1](https://www.nuget.org/packages/NepDate/2.0.1)
I was actually working on verifying all the dates before publishing. But here you go for now.

**Comment by neapes** [comment]
@TheCrossLegCoder thanks for quick action. 

FYI @dgfool
